apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: webhooker
  name: webhooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhooker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        app: webhooker
    spec:
      containers:
      - image: docker.io/yxty/k8s/webhooker:v0.1
        imagePullPolicy: Always
        name: webhooker
        env:
          - name: GIN_MODE
            value: release
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: host-time
      imagePullSecrets:
      - name: robot-k8s
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: webhooker
  name: webhooker
spec:   
  ports:  
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhooker
  sessionAffinity: None
  type: ClusterIP
